name: PR Changeset Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_changeset:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v41.0.1
        with:
          files: |
            .changeset/**.md

      - name: Check for major changes
        id: check_changeset
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: thinkasany
          REPO: test
          LABEL_NAME: major
        run: |
          files=$ALL_CHANGED_FILES
          echo "File list: $files"
          if grep -q "major" "$files"; then
            major_changes=$(grep "major" $files)
            echo "Found major changes."
            echo "comment=$major_changes" >> $GITHUB_OUTPUT
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${OWNER}/${REPO}/issues/${{ github.event.pull_request.number }}/labels" \
            -f "labels[]=${LABEL_NAME}" \
            -t "${{ secrets.GH_TOKEN }}"
          else
            echo "Not found major changes."
            comment=""
            echo "comment=$comment" >> $GITHUB_OUTPUT
          fi

      - name: update status comment
        if: ${{ steps.check_changeset.outputs.comment != '' }}
        uses: actions-cool/maintain-one-comment@v3
        with:
            token: ${{ secrets.GH_TOKEN }}
            body: |
              @${{ github.actor }}, 本次 PR 的更改包含 major 变更，请确认是否符合预期。
              ___
              @${{ github.actor }}, this PR contains major changes, please confirm if it is as expected.
              ```md

              ${{ steps.check_changeset.outputs.comment }}

              ```
              <!-- AUTO_CHANGESET_CHECK_HOOK -->
            body-include: '<!-- AUTO_CHANGESET_CHECK_HOOK -->'
            number: ${{ github.event.pull_request.number }}

      - name: Delete comment
        if: ${{ steps.check_changeset.outputs.comment == '' }}
        uses: actions-cool/maintain-one-comment@v3
        with:
            token: ${{ secrets.GH_TOKEN }}
            body-include: '<!-- AUTO_CHANGESET_CHECK_HOOK -->'
            number: ${{ github.event.pull_request.number }}
            delete: true

      - name: Delete label
        if: ${{ steps.check_changeset.outputs.comment == '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: thinkasany
          REPO: test
          LABEL_NAME: major
        run: |
            echo "Deleting label..."
            gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/${OWNER}/${REPO}/labels/${LABEL_NAME}" \
              -t "${GH_TOKEN}" || true
         
