name: Send DingTalk Message
on:
    workflow_dispatch:
    schedule:
      - cron: '30 1 * * *'  

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to DingTalk
        uses: actions/github-script@v7
        env:
            DINGDING_BOT_TOKEN: ${{ secrets.DINGDING_BOT_TOKEN }}
            actionTitle: '近 7 天未确认的 issue'
        with:
          script: |
            const { data } = await axios.get('https://api.github.com/search/issues?q=repo:ant-design/ant-design&is:open+is:issue+label:unconfirmed&per_page=100')
            const issueList = [];
            for (const item of data.items) {
                const { created_at, html_url, pull_request, state, title } = item;
                const createdAt = new Date(created_at);
                const now = new Date();
                const diffTime = Math.abs(now - createdAt);
                const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 

                if (diffDays > 7) {
                    break;
                }

                if (!pull_request && !html_url.includes('pull') && state === 'open') {
                    issueList.push({
                        html_url,
                        created_at,
                        title
                    })
                }
            }

            const markdownList = `<h2>${actionTitle}</h2>\n\n` + issueList.map(issue => `- [${issue.title}](${issue.html_url})`).join('\n');
            console.log(markdownList);

            try {
                await axios.post(
                    `https://oapi.dingtalk.com/robot/send?access_token=${dingdingTokenKey}`,
                    {
                      msgtype: 'markdown',
                      markdown: {
                        title: actionTitle,
                        text: markdownList,
                      },
                    },
                );
            } catch (error) {
                console.log('发送失败, error:', error);
            }