
name: Public Npm

on:
  create:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@master

      - name: Install and Build 
        run: |
          npm install
          npm run build # 这是我的项目的打包命令，你也可以改成你的

      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致

