name: Verify Files modify

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  verify:
    if: github.event.pull_request.user.login != 'renovate[bot]'
    permissions:
      pull-requests: write  # for actions-cool/verify-files-modify to update status of PRs
    runs-on: ubuntu-latest
    steps:
      - name: verify-version
        uses: thinkasany/verify-files-modify@refs/heads/count
        with:
          forbid-paths: '.github/, scripts/'
          forbid-files: 'CHANGELOG.zh-CN.md, CHANGELOG.en-US.md, LICENSE, README.md'
          skip-count: 5
          comment-mark: version
          comment: |
            Hi @${{ github.event.pull_request.user.login }}. Thanks for your contribution. The path `.github/` or `scripts/` and `CHANGELOG` is only maintained by team members. This current PR will be closed and team members will help on this.
          close: true
          set-failed: false

